update documentation

diff --git a/.github/workflows/build-simtools-prod.yml b/.github/workflows/build-simtools-prod.yml
--- a/.github/workflows/build-simtools-prod.yml
+++ b/.github/workflows/build-simtools-prod.yml
@@ -124,7 +124,7 @@ jobs:
             fi
             sif_file="${tag_name}.sif"
             apptainer build "${sif_file}" "docker://${image_tag}" || { echo "Failed to build Apptainer image for ${image_tag}" >&2; exit 1; }
-            apptainer push -U "${sif_file}" "oras://${image_tag%:*}:${tag_name}.sif" || { echo "Failed to push Apptainer image for ${image_tag}" >&2; exit 1; }
+            apptainer push -U "${sif_file}" "oras://${image_tag%:*}:${tag_name}" || { echo "Failed to push Apptainer image for ${image_tag}" >&2; exit 1; }
             rm -f "${sif_file}"
           done <<< "${{ steps.meta.outputs.tags }}"
 
