test failing of CI when make seg faults

diff --git a/.github/workflows/CI-docs.yml b/.github/workflows/CI-docs.yml
--- a/.github/workflows/CI-docs.yml
+++ b/.github/workflows/CI-docs.yml
@@ -30,6 +30,11 @@ jobs:
         shell: bash -l {0}
         run: |
           make -C docs/ html
+          exit_code=$?
+          if [ $exit_code -ne 5 ]; then
+            echo "Make command failed with exit code $exit_code"
+            exit $exit_code
+          fi
           touch docs/build/html/.nojekyll
 
       - name: Deploy to gihub pages
